"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DashboardLayout from './component/DashboardLayout'

import StyledComponentsRegistry from './registry'
import { useAuth } from './context/auth'
import Login from './login/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isAuthenticated = useAuth();

  
  return (
    <html lang="en">
      <body className={inter.className}>
      <StyledComponentsRegistry>
       
       
        {children}
       
      
        
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
